# gradle tweaks
org.gradle.daemon            = true
org.gradle.configureondemand = true
org.gradle.parallel          = true
android.enableBuildCache     = true
org.gradle.caching           = true
org.gradle.jvmargs           = -Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# dependencies
dep-jna=4.5.0
dep-netty=4.2.0.Alpha2
dep-zstd=1.5.2-1
dep-gson=2.13.1

# Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true



